workflows:
  build-android-apk:
    name: Build Android APK (Flutter 3.38.5)
    environment:
      flutter: "3.38.5"
      java: 17
    scripts:
      - name: Flutter version
        script: flutter --version

      - name: Clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build APK (release)
        script: flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
